# Generated by Django 4.2.4 on 2023-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_list_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='checked',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
