# Generated by Django 4.2.4 on 2023-08-17 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0003_list_checked_list_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='list',
        ),
        migrations.AddField(
            model_name='list',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='shoppinglist.product'),
        ),
    ]
