# Generated by Django 4.2.4 on 2023-08-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_remove_product_list_list_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoppinglist.list'),
        ),
    ]
