# Generated by Django 4.2.4 on 2023-08-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0007_product_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
