# Generated by Django 4.2.4 on 2023-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0008_alter_product_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
